name: Build & Push to ghcr.io

on:
  push:
    branches: [ master ]   # 任何推送到 main 都会触发
  workflow_dispatch:     # 也可以手动点 Run workflow

env:
  IMAGE_NAME: mixapi     # 最终镜像名 = ghcr.io/你的用户名/mixapi

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write     # 关键：允许写入 ghcr

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}          # 自动取当前用户
          password: ${{ secrets.GITHUB_TOKEN }}  # 系统自动生成，无需手动 PAT

      - name: 构建并推送
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:latest
            ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
